from django.db import models

class Prescriber(models.Model):
    npi = models.AutoField(primary_key=True)
    fname = models.CharField(max_length=11)
    lname = models.CharField(max_length=11)
    gender = models.CharField(max_length=1)
    state = models.CharField(max_length=2)
    specialty = models.CharField(max_length=62)
    isopiodprescriber = models.CharField(max_length=5)
    totalperscriptions = models.IntegerField()
    abilify = models.IntegerField(null=True, blank=True, default=0)
    acetaminophencodeine = models.IntegerField(null=True, blank=True, default=0)
    acyclovir = models.IntegerField(null=True, blank=True, default=0)
    advairdiskus = models.IntegerField(null=True, blank=True, default=0)
    aggrenox = models.IntegerField(null=True, blank=True, default=0)
    alendronatesodium = models.IntegerField(null=True, blank=True, default=0)
    allopurinol = models.IntegerField(null=True, blank=True, default=0)
    alprazolam = models.IntegerField(null=True, blank=True, default=0)
    amiodaronehcl = models.IntegerField(null=True, blank=True, default=0)
    amitriptylinehcl = models.IntegerField(null=True, blank=True, default=0)
    amlodipinebesylate = models.IntegerField(null=True, blank=True, default=0)
    amlodipinebesylatebenazepril = models.IntegerField(null=True, blank=True, default=0)
    amoxicillin = models.IntegerField(null=True, blank=True, default=0)
    amoxtrpotassiumclavulanate = models.IntegerField(null=True, blank=True, default=0)
    amphetaminesaltcombo = models.IntegerField(null=True, blank=True, default=0)
    atenolol = models.IntegerField(null=True, blank=True, default=0)
    atorvastatincalcium = models.IntegerField(null=True, blank=True, default=0)
    avodart = models.IntegerField(null=True, blank=True, default=0)
    azithromycin = models.IntegerField(null=True, blank=True, default=0)
    baclofen = models.IntegerField(null=True, blank=True, default=0)
    bdultrafinepenneedle = models.IntegerField(null=True, blank=True, default=0)
    benazeprilhcl = models.IntegerField(null=True, blank=True, default=0)
    benicar = models.IntegerField(null=True, blank=True, default=0)
    benicarhct = models.IntegerField(null=True, blank=True, default=0)
    benztropinemesylate = models.IntegerField(null=True, blank=True, default=0)
    bisoprololhydrochlorothiazide = models.IntegerField(null=True, blank=True, default=0)
    brimonidinetartrate = models.IntegerField(null=True, blank=True, default=0)
    bumetanide = models.IntegerField(null=True, blank=True, default=0)
    bupropionhclsr = models.IntegerField(null=True, blank=True, default=0)
    bupropionxl = models.IntegerField(null=True, blank=True, default=0)
    buspironehcl = models.IntegerField(null=True, blank=True, default=0)
    bystolic = models.IntegerField(null=True, blank=True, default=0)
    carbamazepine = models.IntegerField(null=True, blank=True, default=0)
    carbidopalevodopa = models.IntegerField(null=True, blank=True, default=0)
    carisoprodol = models.IntegerField(null=True, blank=True, default=0)
    cartiaxt = models.IntegerField(null=True, blank=True, default=0)
    carvedilol = models.IntegerField(null=True, blank=True, default=0)
    cefuroxime = models.IntegerField(null=True, blank=True, default=0)
    celebrex = models.IntegerField(null=True, blank=True, default=0)
    cephalexin = models.IntegerField(null=True, blank=True, default=0)
    chlorhexidinegluconate = models.IntegerField(null=True, blank=True, default=0)
    chlorthalidone = models.IntegerField(null=True, blank=True, default=0)
    cilostazol = models.IntegerField(null=True, blank=True, default=0)
    ciprofloxacinhcl = models.IntegerField(null=True, blank=True, default=0)
    citalopramhbr = models.IntegerField(null=True, blank=True, default=0)
    clindamycinhcl = models.IntegerField(null=True, blank=True, default=0)
    clobetasolpropionate = models.IntegerField(null=True, blank=True, default=0)
    clonazepam = models.IntegerField(null=True, blank=True, default=0)
    clonidinehcl = models.IntegerField(null=True, blank=True, default=0)
    clopidogrel = models.IntegerField(null=True, blank=True, default=0)
    clotrimazolebetamethasone = models.IntegerField(null=True, blank=True, default=0)
    colcrys = models.IntegerField(null=True, blank=True, default=0)
    combiventrespimat = models.IntegerField(null=True, blank=True, default=0)
    crestor = models.IntegerField(null=True, blank=True, default=0)
    cyclobenzaprinehcl = models.IntegerField(null=True, blank=True, default=0)
    dexilant = models.IntegerField(null=True, blank=True, default=0)
    diazepam = models.IntegerField(null=True, blank=True, default=0)
    diclofenacsodium = models.IntegerField(null=True, blank=True, default=0)
    dicyclominehcl = models.IntegerField(null=True, blank=True, default=0)
    digox = models.IntegerField(null=True, blank=True, default=0)
    digoxin = models.IntegerField(null=True, blank=True, default=0)
    diltiazem24hrcd = models.IntegerField(null=True, blank=True, default=0)
    diltiazem24hrer = models.IntegerField(null=True, blank=True, default=0)
    diltiazemer = models.IntegerField(null=True, blank=True, default=0)
    diltiazemhcl = models.IntegerField(null=True, blank=True, default=0)
    diovan = models.IntegerField(null=True, blank=True, default=0)
    diphenoxylateatropine = models.IntegerField(null=True, blank=True, default=0)
    divalproexsodium = models.IntegerField(null=True, blank=True, default=0)
    divalproexsodiumer = models.IntegerField(null=True, blank=True, default=0)
    donepezilhcl = models.IntegerField(null=True, blank=True, default=0)
    dorzolamidetimolol = models.IntegerField(null=True, blank=True, default=0)
    doxazosinmesylate = models.IntegerField(null=True, blank=True, default=0)
    doxepinhcl = models.IntegerField(null=True, blank=True, default=0)
    doxycyclinehyclate = models.IntegerField(null=True, blank=True, default=0)
    duloxetinehcl = models.IntegerField(null=True, blank=True, default=0)
    enalaprilmaleate = models.IntegerField(null=True, blank=True, default=0)
    escitalopramoxalate = models.IntegerField(null=True, blank=True, default=0)
    estradiol = models.IntegerField(null=True, blank=True, default=0)
    exelon = models.IntegerField(null=True, blank=True, default=0)
    famotidine = models.IntegerField(null=True, blank=True, default=0)
    felodipineer = models.IntegerField(null=True, blank=True, default=0)
    fenofibrate = models.IntegerField(null=True, blank=True, default=0)
    fentanyl = models.IntegerField(null=True, blank=True, default=0)
    finasteride = models.IntegerField(null=True, blank=True, default=0)
    floventhfa = models.IntegerField(null=True, blank=True, default=0)
    fluconazole = models.IntegerField(null=True, blank=True, default=0)
    fluoxetinehcl = models.IntegerField(null=True, blank=True, default=0)
    fluticasonepropionate = models.IntegerField(null=True, blank=True, default=0)
    furosemide = models.IntegerField(null=True, blank=True, default=0)
    gabapentin = models.IntegerField(null=True, blank=True, default=0)
    gemfibrozil = models.IntegerField(null=True, blank=True, default=0)
    glimepiride = models.IntegerField(null=True, blank=True, default=0)
    glipizide = models.IntegerField(null=True, blank=True, default=0)
    glipizideer = models.IntegerField(null=True, blank=True, default=0)
    glipizidexl = models.IntegerField(null=True, blank=True, default=0)
    glyburide = models.IntegerField(null=True, blank=True, default=0)
    haloperidol = models.IntegerField(null=True, blank=True, default=0)
    humalog = models.IntegerField(null=True, blank=True, default=0)
    hydralazinehcl = models.IntegerField(null=True, blank=True, default=0)
    hydrochlorothiazide = models.IntegerField(null=True, blank=True, default=0)
    hydrocodoneacetaminophen = models.IntegerField(null=True, blank=True, default=0)
    hydrocortisone = models.IntegerField(null=True, blank=True, default=0)
    hydromorphonehcl = models.IntegerField(null=True, blank=True, default=0)
    hydroxyzinehcl = models.IntegerField(null=True, blank=True, default=0)
    ibandronatesodium = models.IntegerField(null=True, blank=True, default=0)
    ibuprofen = models.IntegerField(null=True, blank=True, default=0)
    insulinsyringe = models.IntegerField(null=True, blank=True, default=0)
    ipratropiumbromide = models.IntegerField(null=True, blank=True, default=0)
    irbesartan = models.IntegerField(null=True, blank=True, default=0)
    isosorbidemononitrateer = models.IntegerField(null=True, blank=True, default=0)
    jantoven = models.IntegerField(null=True, blank=True, default=0)
    janumet = models.IntegerField(null=True, blank=True, default=0)
    januvia = models.IntegerField(null=True, blank=True, default=0)
    ketoconazole = models.IntegerField(null=True, blank=True, default=0)
    klorcon10 = models.IntegerField(null=True, blank=True, default=0)
    klorconm10 = models.IntegerField(null=True, blank=True, default=0)
    klorconm20 = models.IntegerField(null=True, blank=True, default=0)
    labetalolhcl = models.IntegerField(null=True, blank=True, default=0)
    lactulose = models.IntegerField(null=True, blank=True, default=0)
    lamotrigine = models.IntegerField(null=True, blank=True, default=0)
    lansoprazole = models.IntegerField(null=True, blank=True, default=0)
    lantus = models.IntegerField(null=True, blank=True, default=0)
    lantussolostar = models.IntegerField(null=True, blank=True, default=0)
    latanoprost = models.IntegerField(null=True, blank=True, default=0)
    levemir = models.IntegerField(null=True, blank=True, default=0)
    levemirflexpen = models.IntegerField(null=True, blank=True, default=0)
    levetiracetam = models.IntegerField(null=True, blank=True, default=0)
    levofloxacin = models.IntegerField(null=True, blank=True, default=0)
    levothyroxinesodium = models.IntegerField(null=True, blank=True, default=0)
    lidocaine = models.IntegerField(null=True, blank=True, default=0)
    lisinopril = models.IntegerField(null=True, blank=True, default=0)
    lisinoprilhydrochlorothiazide = models.IntegerField(null=True, blank=True, default=0)
    lithiumcarbonate = models.IntegerField(null=True, blank=True, default=0)
    lorazepam = models.IntegerField(null=True, blank=True, default=0)
    losartanhydrochlorothiazide = models.IntegerField(null=True, blank=True, default=0)
    losartanpotassium = models.IntegerField(null=True, blank=True, default=0)
    lovastatin = models.IntegerField(null=True, blank=True, default=0)
    lovaza = models.IntegerField(null=True, blank=True, default=0)
    lumigan = models.IntegerField(null=True, blank=True, default=0)
    lyrica = models.IntegerField(null=True, blank=True, default=0)
    meclizinehcl = models.IntegerField(null=True, blank=True, default=0)
    meloxicam = models.IntegerField(null=True, blank=True, default=0)
    metforminhcl = models.IntegerField(null=True, blank=True, default=0)
    metforminhcler = models.IntegerField(null=True, blank=True, default=0)
    methadonehcl = models.IntegerField(null=True, blank=True, default=0)
    methocarbamol = models.IntegerField(null=True, blank=True, default=0)
    methotrexate = models.IntegerField(null=True, blank=True, default=0)
    methylprednisolone = models.IntegerField(null=True, blank=True, default=0)
    metoclopramidehcl = models.IntegerField(null=True, blank=True, default=0)
    metolazone = models.IntegerField(null=True, blank=True, default=0)
    metoprololsuccinate = models.IntegerField(null=True, blank=True, default=0)
    metoprololtartrate = models.IntegerField(null=True, blank=True, default=0)
    metronidazole = models.IntegerField(null=True, blank=True, default=0)
    mirtazapine = models.IntegerField(null=True, blank=True, default=0)
    montelukastsodium = models.IntegerField(null=True, blank=True, default=0)
    morphinesulfate = models.IntegerField(null=True, blank=True, default=0)
    morphinesulfateer = models.IntegerField(null=True, blank=True, default=0)
    mupirocin = models.IntegerField(null=True, blank=True, default=0)
    nabumetone = models.IntegerField(null=True, blank=True, default=0)
    namenda = models.IntegerField(null=True, blank=True, default=0)
    namendaxr = models.IntegerField(null=True, blank=True, default=0)
    naproxen = models.IntegerField(null=True, blank=True, default=0)
    nasonex = models.IntegerField(null=True, blank=True, default=0)
    nexium = models.IntegerField(null=True, blank=True, default=0)
    niaciner = models.IntegerField(null=True, blank=True, default=0)
    nifedicalxl = models.IntegerField(null=True, blank=True, default=0)
    nifedipineer = models.IntegerField(null=True, blank=True, default=0)
    nitrofurantoinmonomacro = models.IntegerField(null=True, blank=True, default=0)
    nitrostat = models.IntegerField(null=True, blank=True, default=0)
    nortriptylinehcl = models.IntegerField(null=True, blank=True, default=0)
    novolog = models.IntegerField(null=True, blank=True, default=0)
    novologflexpen = models.IntegerField(null=True, blank=True, default=0)
    nystatin = models.IntegerField(null=True, blank=True, default=0)
    olanzapine = models.IntegerField(null=True, blank=True, default=0)
    omeprazole = models.IntegerField(null=True, blank=True, default=0)
    ondansetronhcl = models.IntegerField(null=True, blank=True, default=0)
    ondansetronodt = models.IntegerField(null=True, blank=True, default=0)
    onglyza = models.IntegerField(null=True, blank=True, default=0)
    oxcarbazepine = models.IntegerField(null=True, blank=True, default=0)
    oxybutyninchloride = models.IntegerField(null=True, blank=True, default=0)
    oxybutyninchlorideer = models.IntegerField(null=True, blank=True, default=0)
    oxycodoneacetaminophen = models.IntegerField(null=True, blank=True, default=0)
    oxycodonehcl = models.IntegerField(null=True, blank=True, default=0)
    oxycontin = models.IntegerField(null=True, blank=True, default=0)
    pantoprazolesodium = models.IntegerField(null=True, blank=True, default=0)
    paroxetinehcl = models.IntegerField(null=True, blank=True, default=0)
    phenobarbital = models.IntegerField(null=True, blank=True, default=0)
    phenytoinsodiumextended = models.IntegerField(null=True, blank=True, default=0)
    pioglitazonehcl = models.IntegerField(null=True, blank=True, default=0)
    polyethyleneglycol3350 = models.IntegerField(null=True, blank=True, default=0)
    potassiumchloride = models.IntegerField(null=True, blank=True, default=0)
    pradaxa = models.IntegerField(null=True, blank=True, default=0)
    pramipexoledihydrochloride = models.IntegerField(null=True, blank=True, default=0)
    pravastatinsodium = models.IntegerField(null=True, blank=True, default=0)
    prednisone = models.IntegerField(null=True, blank=True, default=0)
    premarin = models.IntegerField(null=True, blank=True, default=0)
    primidone = models.IntegerField(null=True, blank=True, default=0)
    proairhfa = models.IntegerField(null=True, blank=True, default=0)
    promethazinehcl = models.IntegerField(null=True, blank=True, default=0)
    propranololhcl = models.IntegerField(null=True, blank=True, default=0)
    propranololhcler = models.IntegerField(null=True, blank=True, default=0)
    quetiapinefumarate = models.IntegerField(null=True, blank=True, default=0)
    quinaprilhcl = models.IntegerField(null=True, blank=True, default=0)
    raloxifenehcl = models.IntegerField(null=True, blank=True, default=0)
    ramipril = models.IntegerField(null=True, blank=True, default=0)
    ranexa = models.IntegerField(null=True, blank=True, default=0)
    ranitidinehcl = models.IntegerField(null=True, blank=True, default=0)
    restasis = models.IntegerField(null=True, blank=True, default=0)
    risperidone = models.IntegerField(null=True, blank=True, default=0)
    ropinirolehcl = models.IntegerField(null=True, blank=True, default=0)
    seroquelxr = models.IntegerField(null=True, blank=True, default=0)
    sertralinehcl = models.IntegerField(null=True, blank=True, default=0)
    simvastatin = models.IntegerField(null=True, blank=True, default=0)
    sotalol = models.IntegerField(null=True, blank=True, default=0)
    spiriva = models.IntegerField(null=True, blank=True, default=0)
    spironolactone = models.IntegerField(null=True, blank=True, default=0)
    sucralfate = models.IntegerField(null=True, blank=True, default=0)
    sulfamethoxazoletrimethoprim = models.IntegerField(null=True, blank=True, default=0)
    sumatriptansuccinate = models.IntegerField(null=True, blank=True, default=0)
    symbicort = models.IntegerField(null=True, blank=True, default=0)
    synthroid = models.IntegerField(null=True, blank=True, default=0)
    tamsulosinhcl = models.IntegerField(null=True, blank=True, default=0)
    temazepam = models.IntegerField(null=True, blank=True, default=0)
    terazosinhcl = models.IntegerField(null=True, blank=True, default=0)
    timololmaleate = models.IntegerField(null=True, blank=True, default=0)
    tizanidinehcl = models.IntegerField(null=True, blank=True, default=0)
    tolterodinetartrateer = models.IntegerField(null=True, blank=True, default=0)
    topiramate = models.IntegerField(null=True, blank=True, default=0)
    toprolxl = models.IntegerField(null=True, blank=True, default=0)
    torsemide = models.IntegerField(null=True, blank=True, default=0)
    tramadolhcl = models.IntegerField(null=True, blank=True, default=0)
    travatanz = models.IntegerField(null=True, blank=True, default=0)
    trazodonehcl = models.IntegerField(null=True, blank=True, default=0)
    triamcinoloneacetonide = models.IntegerField(null=True, blank=True, default=0)
    triamterenehydrochlorothiazid = models.IntegerField(null=True, blank=True, default=0)
    valacyclovir = models.IntegerField(null=True, blank=True, default=0)
    valsartan = models.IntegerField(null=True, blank=True, default=0)
    valsartanhydrochlorothiazide = models.IntegerField(null=True, blank=True, default=0)
    venlafaxinehcl = models.IntegerField(null=True, blank=True, default=0)
    venlafaxinehcler = models.IntegerField(null=True, blank=True, default=0)
    ventolinhfa = models.IntegerField(null=True, blank=True, default=0)
    verapamiler = models.IntegerField(null=True, blank=True, default=0)
    vesicare = models.IntegerField(null=True, blank=True, default=0)
    voltaren = models.IntegerField(null=True, blank=True, default=0)
    vytorin = models.IntegerField(null=True, blank=True, default=0)
    warfarinsodium = models.IntegerField(null=True, blank=True, default=0)
    xarelto = models.IntegerField(null=True, blank=True, default=0)
    zetia = models.IntegerField(null=True, blank=True, default=0)
    ziprasidonehcl = models.IntegerField(null=True, blank=True, default=0)
    zolpidemtartrate = models.IntegerField(null=True, blank=True, default=0)

    class Meta:
        db_table = 'prescriber'

    def __str__(self):
        return (self.fname + ' ' + self.lname)



class Credential(models.Model):
    id = models.IntegerField(primary_key=True)
    npi = models.ForeignKey('Prescriber', models.CASCADE, db_column='npi')
    credentials = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        db_table = 'credential'


class Drug(models.Model):
    drugname = models.CharField(primary_key=True, max_length=30)
    isopiod = models.CharField(max_length=5)

    class Meta:
        db_table = 'drug'

    def __str__(self):
        return (self.drugname)

class Statedata(models.Model):
    stateabbrev = models.CharField(primary_key=True, max_length=2)
    population = models.IntegerField()
    deaths = models.IntegerField()

    class Meta:
        db_table = 'statedata'

    def __str__(self):
        return (self.stateabbrev)


class Statenames(models.Model):
    stateabbrev = models.OneToOneField(Statedata, models.DO_NOTHING, db_column='stateabbrev', primary_key=True)
    state = models.CharField(max_length=14)

    class Meta:
        db_table = 'statenames'
    
    def __str__(self):
        return (self.state)


class Triple(models.Model):
    id = models.IntegerField(primary_key=True)
    npi = models.ForeignKey(Prescriber, models.CASCADE, db_column='npi')
    drugname = models.ForeignKey(Drug, models.DO_NOTHING, db_column='drugname')
    qty = models.IntegerField()

    class Meta:
        db_table = 'triple'